name: CI
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - run: swift build
